{
 "title": "COE - Kafka endpoint",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Kafka upload health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_file_conns_freed[60s])",
     "legendFormat": "Kafka error file connections"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_meta_conns_freed[60s])",
     "legendFormat": "Kafka error meta connections"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_meta_response[60s])",
     "legendFormat": "Kafka error meta response"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_part_leader[60s])",
     "legendFormat": "Kafka error partition leader"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_pushfile[60s])",
     "legendFormat": "Kafka error pushfile"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_pushfiletopic_notpresent[60s])",
     "legendFormat": "Kafka error topic not present"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_err_kafka_server_info[60s])",
     "legendFormat": "Kafka error server info"
    }
   ]
  },
  {
   "title": "Kafka upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile[60s])",
     "legendFormat": "Kafka tot push"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_succ[60s])",
     "legendFormat": "Kafka push success"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_removed[60s])",
     "legendFormat": "Kafka avro files cleaned"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_avrofile_processed[60s])",
     "legendFormat": "Kafka avro files created"
    }
   ]
  },
  {
   "title": "Kafka avro data push",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_kafka_pushfile_sz[60s])",
     "legendFormat": "Kafka avro data push"
    }
   ]
  },
  {
   "title": "HTTP Req Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_http_reqs_done[40s])",
     "legendFormat": "HTTP Request rate"
    }
   ]
  },
  {
   "title": "HTTP anomalous transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_anomalous_trans_recvd[60s])",
     "legendFormat": "HTTP anomalous trans"
    }
   ]
  },
  {
   "title": "TCP records dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_all_tcp_dropped[60s])",
     "legendFormat": "TCP recs dropped"
    }
   ]
  }
 ]
}