{
 "title": "ADC Health Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "ALERTS", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_use" }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "mem_cur_usedsize" }
   ]
  },
  {
   "title": "Vserver/Service Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "si_cur_state", "legendFormat": "{{Schema}}:{{EntityName}}" }
   ]
  },
  {
   "title": "Server Farm health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "si_tot_svr_busy_err{Schema=\"server_svc_cfg\"}",
     "legendFormat": "Server busy error"
    },
    {
     "expr": "si_tot_ttlb_tolerating_transactions{Schema=\"server_svc_cfg\"}",
     "legendFormat": "Server RTT >3s"
    },
    {
     "expr": "si_tot_ttlb_frustrating_transactions{Schema=\"server_svc_cfg\"}",
     "legendFormat": "Server RTT >5s"
    }
   ]
  },
  {
   "title": "Connections - Client Vs Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "si_cur_Clients",
     "legendFormat": "Client Conn - {{Schema}}:{{EntityName}}"
    },
    {
     "expr": "si_cur_Servers",
     "legendFormat": "Server Conn - {{Schema}}:{{EntityName}}"
    }
   ]
  },
  {
   "title": "Tcp Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(tcp_tot_rxpkts[1m])", "legendFormat": "Tcp RXPkts - {{sysId}}" }
   ]
  }
 ]
}