{
 "title": "COE - Elasticsearch endpoint",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Elasticsearch upload health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_elk_health_bad",
     "legendFormat": "ES health bad"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_elk_connected",
     "legendFormat": "ES connection error"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_elk_data_resp",
     "legendFormat": "ES data resp error"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_err_elk_data_uploadmsg",
     "legendFormat": "ES data upload error"
    }
   ]
  },
  {
   "title": "Elasticsearch uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lstreamcpp_counters_lstrmcppd_tot_elk_data_uploadmsg",
     "legendFormat": "ES upload attempts"
    },
    {
     "expr": "lstreamcpp_counters_lstrmcppd_tot_elk_data_resp_success",
     "legendFormat": "ES upload success"
    }
   ]
  },
  {
   "title": "ES Json data push",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_json_buf_freed[60s]) * 32 * 1024 ",
     "legendFormat": "ES Json buffer freed"
    },
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_json_buf_alloc[60s])  * 32 * 1024",
     "legendFormat": "ES Json buffer alloc"
    }
   ]
  },
  {
   "title": "HTTP Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_http_reqs_done[40s])",
     "legendFormat": "HTTP Request rate"
    }
   ]
  },
  {
   "title": "HTTP Anomalous transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_anomalous_trans_recvd[60s])",
     "legendFormat": "HTTP Anomalous transactions"
    }
   ]
  },
  {
   "title": "TCP Records dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lstreamcpp_counters_lstrmcppd_tot_all_tcp_dropped[60s])",
     "legendFormat": "TCP records dropped"
    }
   ]
  }
 ]
}